# Generated by Django 4.0.3 on 2022-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='question_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Multi Choice'), (2, 'Fill Blank'), (3, 'True False'), (4, 'Short Answer')], default=4, null=True),
        ),
    ]
